from __future__ import annotations

from typing import List

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.constants import AI_DISCLAIMER_SHORT, DISCLAIMER
from app.core.deps import get_current_user, owned_or_404
from app.core.rate_limit import enforce_ai_limits
from app.db.session import get_db
from app.models.ai import AIConversation, AIMessage
from app.models.user import User
from app.schemas.common import DeletedResponse
from app.schemas.finance import ChatMessageOut, ChatRequest, ChatResponse, ConversationOut
from app.services.ai.coach import answer_question, suggested_questions
from app.services.finance.context import build_financial_context

router = APIRouter(prefix="/ai", tags=["ai-coach"])


@router.get("/status")
def ai_status(user: User = Depends(get_current_user)):
    """Tells the UI which engine is answering, so the badge is never a guess."""
    return {
        "ai_enabled": settings.ai_enabled,
        "model": settings.OPENAI_MODEL if settings.ai_enabled else None,
        "mode": "AI" if settings.ai_enabled else "RULE_BASED",
        "description": (
            "Answers are generated by the language model using your financial data, with purchase "
            "verdicts fixed by the app's own engine."
            if settings.ai_enabled
            else "No AI key is configured, so answers come from the app's built-in financial engine. "
            "Every number is computed from your data - nothing is invented."
        ),
        "rate_limit": {
            "per_minute": settings.AI_RATE_LIMIT_PER_MINUTE,
            "per_day": settings.AI_RATE_LIMIT_PER_DAY,
        },
        "disclaimer": DISCLAIMER,
    }


@router.get("/suggestions")
def suggestions(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    ctx = build_financial_context(db, user)
    return {"suggestions": suggested_questions(ctx)}


@router.get("/conversations", response_model=List[ConversationOut])
def list_conversations(db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    rows = db.scalars(
        select(AIConversation)
        .where(AIConversation.user_id == user.id)
        .order_by(AIConversation.updated_at.desc())
        .limit(50)
    )
    return [ConversationOut.model_validate(r) for r in rows]


@router.get("/conversations/{conversation_id}/messages", response_model=List[ChatMessageOut])
def list_messages(
    conversation_id: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)
):
    conversation = owned_or_404(db.get(AIConversation, conversation_id), user, "Conversation")
    rows = db.scalars(
        select(AIMessage)
        .where(AIMessage.conversation_id == conversation.id)
        .order_by(AIMessage.created_at.asc())
    )
    return [ChatMessageOut.model_validate(r) for r in rows]


@router.delete("/conversations/{conversation_id}", response_model=DeletedResponse)
def delete_conversation(
    conversation_id: str, db: Session = Depends(get_db), user: User = Depends(get_current_user)
):
    conversation = owned_or_404(db.get(AIConversation, conversation_id), user, "Conversation")
    db.delete(conversation)
    db.commit()
    return DeletedResponse(id=conversation_id)


@router.post("/chat", response_model=ChatResponse)
def chat(payload: ChatRequest, db: Session = Depends(get_db), user: User = Depends(get_current_user)):
    """
    Asks the Finance AI Coach a question.

    The user's real financial data is assembled server-side; the client never
    supplies the figures, so it cannot manipulate the answer.
    """
    enforce_ai_limits(user.id, settings.AI_RATE_LIMIT_PER_MINUTE, settings.AI_RATE_LIMIT_PER_DAY)

    if payload.conversation_id:
        conversation = owned_or_404(
            db.get(AIConversation, payload.conversation_id), user, "Conversation"
        )
    else:
        conversation = AIConversation(
            user_id=user.id, title=payload.message[:60].strip() or "New conversation"
        )
        db.add(conversation)
        db.flush()

    history = [
        {"role": m.role, "content": m.content}
        for m in db.scalars(
            select(AIMessage)
            .where(AIMessage.conversation_id == conversation.id)
            .order_by(AIMessage.created_at.desc())
            .limit(6)
        )
    ][::-1]

    db.add(
        AIMessage(
            conversation_id=conversation.id,
            role="user",
            content=payload.message,
            generated_by="RULE_BASED",
        )
    )

    ctx = build_financial_context(db, user)
    answer, generated_by = answer_question(ctx, payload.message, history)

    assistant = AIMessage(
        conversation_id=conversation.id,
        role="assistant",
        content=answer,
        generated_by=generated_by,
    )
    db.add(assistant)
    db.commit()
    db.refresh(assistant)

    return ChatResponse(
        conversation_id=conversation.id,
        message=ChatMessageOut.model_validate(assistant),
        generated_by=generated_by,
        disclaimer=AI_DISCLAIMER_SHORT,
    )
