from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)


class Quote:
    """A quote that actually came from a market data provider."""

    def __init__(self, symbol: str, price: float, previous_close: Optional[float], as_of: datetime):
        self.symbol = symbol
        self.price = price
        self.previous_close = previous_close
        self.as_of = as_of

    def as_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "price": self.price,
            "previous_close": self.previous_close,
            "as_of": self.as_of,
            "source": "LIVE_MARKET",
            "provider": settings.MARKET_DATA_PROVIDER,
        }


def is_enabled() -> bool:
    return settings.market_data_enabled


async def fetch_quote(symbol: str) -> Optional[Quote]:
    """
    Fetches a live quote.

    Returns None when no provider is configured, the symbol is unknown, or the
    request fails. The caller must then keep the user-entered price - the app
    never substitutes an invented number for a real one.
    """
    if not is_enabled():
        return None

    symbol = symbol.strip().upper()
    if not symbol:
        return None

    provider = settings.MARKET_DATA_PROVIDER.lower()
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            if provider == "finnhub":
                resp = await client.get(
                    "https://finnhub.io/api/v1/quote",
                    params={"symbol": symbol, "token": settings.MARKET_DATA_API_KEY},
                )
                resp.raise_for_status()
                data = resp.json()
                price = float(data.get("c") or 0)
                prev = float(data.get("pc") or 0) or None
                if price <= 0:
                    return None
                return Quote(symbol, round(price, 2), round(prev, 2) if prev else None, datetime.utcnow())

            logger.warning("Unsupported market data provider: %s", provider)
            return None
    except Exception as exc:
        logger.warning("Quote lookup failed for %s: %s", symbol, exc)
        return None


def provider_status() -> dict:
    return {
        "enabled": is_enabled(),
        "provider": settings.MARKET_DATA_PROVIDER if is_enabled() else None,
        "note": (
            "Live prices are fetched on demand and stamped with the time they were retrieved."
            if is_enabled()
            else "No market data key configured. Every price shown is the one you entered, "
            "labelled 'user-entered'. Prices are never generated by the app."
        ),
    }
